const MAX_GENERATED_IMAGE_BYTES = 5 * 1024 * 1024;
const DATA_URL_PREFIX = /^data:image\/png;base64,([A-Za-z0-9+/]+={0,2})$/;

export function validateSharePayload(payload) {
  if (!payload || typeof payload !== "object") {
    return { valid: false, message: "A generated PNG is required." };
  }
  if (!["pfp", "id-card"].includes(payload.format)) {
    return { valid: false, message: "The selected graphic format is invalid." };
  }
  if (typeof payload.imageDataUrl !== "string") {
    return { valid: false, message: "A generated PNG is required." };
  }

  const match = payload.imageDataUrl.match(DATA_URL_PREFIX);
  if (!match) {
    return { valid: false, message: "Only PNG graphics generated by this tool can be shared." };
  }

  const buffer = Buffer.from(match[1], "base64");
  if (!buffer.length || buffer.length > MAX_GENERATED_IMAGE_BYTES) {
    return { valid: false, message: "This generated image is too large to share. Download it and share manually." };
  }
  // PNG signature prevents a data URL with arbitrary base64 from being stored.
  if (buffer.length < 8 || !buffer.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
    return { valid: false, message: "The generated image could not be verified." };
  }
  return { valid: true, buffer };
}
